### ISSUE TITLE
detect httpclient calls

### ISSUE THREAD

**Issue by gmella** [craigberry/audit_exist_5x_removals#4]
Moving to existdb V5 I still find some httpclient call that fails on runtime.

My xquery code didn't import associated module but use smootly next kind of code:

`let $data := httpclient:get($readme-url, false(), <headers/>)`

Thx

**Comment by craigberry** [comment]
Hmm.  So I guess the httpclient functions were built-ins in eXist 4.x and did not need an import?  Thanks for the heads up.  I will look into adding them to the function list.

**Comment by craigberry** [comment]
Hopefully that commit took care of it -- I don't have any appropriate code to test with.
